"""Add delivery_unit_label to ProjectBillingConfig

Revision ID: 22a49390979b
Revises: c4d8f1a9e6b2
Create Date: 2026-08-24 11:01:07.676576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22a49390979b'
down_revision: Union[str, None] = 'c4d8f1a9e6b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_billing_config', sa.Column('delivery_unit_label', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_billing_config', 'delivery_unit_label')
    # ### end Alembic commands ###
