"""refactor_client_model

Revision ID: 237cd016d1f2
Revises: 09716e9fc2ad
Create Date: 2026-08-20 10:50:35.973392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '237cd016d1f2'
down_revision: Union[str, None] = '09716e9fc2ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('status', sa.String(length=50), nullable=False, server_default='DRAFT'))
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.alter_column('company_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_index('ix_clients_company_name')
        batch_op.create_index(batch_op.f('ix_clients_company_name'), ['company_name'], unique=False)

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_column('billing_type')
        batch_op.drop_column('milestone_id')
        batch_op.drop_column('billing_percentage')

    with op.batch_alter_table('project_milestones', schema=None) as batch_op:
        batch_op.alter_column('source_unit_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_milestones', 'source_unit_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)
    op.add_column('invoices', sa.Column('billing_type', sa.VARCHAR(length=50), nullable=True))
    op.add_column('invoices', sa.Column('milestone_id', sa.VARCHAR(length=36), nullable=True))
    op.add_column('invoices', sa.Column('billing_percentage', sa.NUMERIC(precision=5, scale=2), nullable=True))
    op.create_foreign_key(None, 'invoices', 'project_milestones', ['milestone_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_clients_company_name'), table_name='clients')
    op.create_index('ix_clients_company_name', 'clients', ['company_name'], unique=1)
    op.alter_column('clients', 'company_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('clients', 'status')
    # ### end Alembic commands ###
