"""add_classification_snapshot_fields

Revision ID: 3c7735c402c6
Revises: 237cd016d1f2
Create Date: 2026-08-20 15:51:11.253131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c7735c402c6'
down_revision: Union[str, None] = '237cd016d1f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hsn_sac_master', schema=None) as batch_op:
        batch_op.drop_index('ix_hsn_sac_master_code')
    
    op.drop_table('hsn_sac_master')

    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('billing_classification_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('hsn_sac_code', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('gst_rate', sa.Numeric(precision=5, scale=2), nullable=True))
        batch_op.add_column(sa.Column('classification_source', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key(
            'fk_invoice_items_billing_classification_id', 
            'billing_classifications', 
            ['billing_classification_id'], 
            ['id'], 
            ondelete='RESTRICT'
        )
        batch_op.drop_column('hsn_sac')

    with op.batch_alter_table('project_commercial_components', schema=None) as batch_op:
        batch_op.add_column(sa.Column('billing_classification_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('classification_source', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key(
            'fk_pcc_billing_classification_id', 
            'billing_classifications', 
            ['billing_classification_id'], 
            ['id'], 
            ondelete='RESTRICT'
        )

    with op.batch_alter_table('project_milestones', schema=None) as batch_op:
        batch_op.add_column(sa.Column('billing_classification_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('classification_source', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key(
            'fk_pm_billing_classification_id', 
            'billing_classifications', 
            ['billing_classification_id'], 
            ['id'], 
            ondelete='RESTRICT'
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_milestones', type_='foreignkey')
    op.drop_column('project_milestones', 'classification_source')
    op.drop_column('project_milestones', 'billing_classification_id')
    op.drop_constraint(None, 'project_commercial_components', type_='foreignkey')
    op.drop_column('project_commercial_components', 'classification_source')
    op.drop_column('project_commercial_components', 'billing_classification_id')
    op.add_column('invoice_items', sa.Column('hsn_sac', sa.VARCHAR(length=50), nullable=True))
    op.drop_constraint(None, 'invoice_items', type_='foreignkey')
    op.drop_column('invoice_items', 'classification_source')
    op.drop_column('invoice_items', 'gst_rate')
    op.drop_column('invoice_items', 'hsn_sac_code')
    op.drop_column('invoice_items', 'billing_classification_id')
    op.create_table('hsn_sac_master',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('code', sa.VARCHAR(length=50), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('service_type', sa.VARCHAR(length=100), nullable=False),
    sa.Column('gst_rate', sa.NUMERIC(precision=5, scale=2), nullable=False),
    sa.Column('active', sa.BOOLEAN(), nullable=True),
    sa.Column('effective_from', sa.DATETIME(), nullable=True),
    sa.Column('effective_to', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_hsn_sac_master_code', 'hsn_sac_master', ['code'], unique=1)
    # ### end Alembic commands ###
