"""Add professional invoice fields

Revision ID: 540e5adda193
Revises: d6bb6dfccebd
Create Date: 2026-08-21 15:07:06.829819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '540e5adda193'
down_revision: Union[str, None] = 'd6bb6dfccebd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_items', sa.Column('hours', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('invoices', sa.Column('client_email', sa.String(length=100), nullable=True))
    op.add_column('invoices', sa.Column('client_phone', sa.String(length=50), nullable=True))
    op.add_column('invoices', sa.Column('project_number', sa.String(length=100), nullable=True))
    op.add_column('invoices', sa.Column('project_start_date', sa.DateTime(), nullable=True))
    op.add_column('invoices', sa.Column('project_end_date', sa.DateTime(), nullable=True))
    op.add_column('invoices', sa.Column('bank_name', sa.String(length=255), nullable=True))
    op.add_column('invoices', sa.Column('bank_account_number', sa.String(length=100), nullable=True))
    op.add_column('invoices', sa.Column('bank_ifsc', sa.String(length=50), nullable=True))
    op.add_column('invoices', sa.Column('invoice_terms', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'invoice_terms')
    op.drop_column('invoices', 'bank_ifsc')
    op.drop_column('invoices', 'bank_account_number')
    op.drop_column('invoices', 'bank_name')
    op.drop_column('invoices', 'project_end_date')
    op.drop_column('invoices', 'project_start_date')
    op.drop_column('invoices', 'project_number')
    op.drop_column('invoices', 'client_phone')
    op.drop_column('invoices', 'client_email')
    op.drop_column('invoice_items', 'hours')
    # ### end Alembic commands ###
