"""add task_key to invoice_items

Revision ID: a1fc2f17f82a
Revises: 3c7735c402c6
Create Date: 2026-08-20 17:02:24.906782

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1fc2f17f82a'
down_revision: Union[str, None] = '3c7735c402c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_items', sa.Column('task_key', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice_items', 'task_key')
    # ### end Alembic commands ###
