"""add_requirement_name_to_invoice_item

Revision ID: d6bb6dfccebd
Revises: a1fc2f17f82a
Create Date: 2026-08-21 09:13:58.732477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6bb6dfccebd'
down_revision: Union[str, None] = 'a1fc2f17f82a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_items', sa.Column('requirement_name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice_items', 'requirement_name')
    # ### end Alembic commands ###
