import { useEffect, useRef, useState } from 'react'
import { useParams } from 'react-router-dom'
import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import Topbar from '../components/Topbar'
import Card from '../components/Card'
import Mermaid from '../components/Mermaid'
import HtmlFrame, { type HtmlFrameHandle } from '../components/HtmlFrame'
import { getJobDocument, getDocumentFile, updateDocumentContent, openDocumentPdf } from '../api/client'
import { Editor } from '@toast-ui/react-editor'
import '@toast-ui/editor/dist/toastui-editor.css'

const TYPE_LABEL: Record<string, string> = {
  quotation: 'Quotation',
  brd: 'Business Requirements Document',
  srs: 'Software Requirements Specification',
  invoice: 'Invoice',
}

export default function DocumentView({ source }: { source: 'job' | 'base' }) {
  const params = useParams<{ jobId?: string; baseName?: string; type: string }>()
  const type = params.type as 'quotation' | 'brd' | 'srs' | 'invoice'
  const [content, setContent] = useState<string | null>(null)
  const [editing, setEditing] = useState(false)
  const [draft, setDraft] = useState('')
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const frameRef = useRef<HtmlFrameHandle>(null)
  const editorRef = useRef<Editor>(null)

  const canEdit = source === 'base' && !!params.baseName
  const isInvoice = type === 'invoice'

  useEffect(() => {
    setContent(null)
    setError(null)
    setEditing(false)
    const fetcher =
      source === 'job' && params.jobId
        ? getJobDocument(params.jobId, type as 'quotation' | 'brd' | 'srs')
        : source === 'base' && params.baseName
        ? getDocumentFile(params.baseName, type)
        : Promise.reject(new Error('Missing identifier'))
    fetcher.then(setContent).catch((e) => setError(e.message))
  }, [source, params.jobId, params.baseName, type])

  function download() {
    if (!content) return
    const ext = type === 'invoice' ? 'html' : 'md'
    const blob = new Blob([content], { type: type === 'invoice' ? 'text/html' : 'text/markdown' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${params.baseName || params.jobId}_${type}.${ext}`
    a.click()
    URL.revokeObjectURL(url)
  }

  async function saveEdit() {
    if (!params.baseName) return
    const edited = isInvoice ? frameRef.current?.getHtml() : (editorRef.current?.getInstance().getMarkdown() || draft)
    if (!edited) return
    setSaving(true)
    setError(null)
    try {
      await updateDocumentContent(params.baseName, type, edited)
      setContent(edited)
      setEditing(false)
    } catch (e: any) {
      setError(e.message)
    } finally {
      setSaving(false)
    }
  }

  return (
    <div className="flex-1">
      <Topbar title={TYPE_LABEL[type] ?? type} subtitle="Auto-generated by Pixous Technologies — fully editable before export." />
      <div className="p-8 max-w-4xl">
        <div className="flex justify-end gap-3 mb-4">
          {canEdit &&
            (editing ? (
              <>
                <button
                  onClick={() => setEditing(false)}
                  className="text-sm font-medium bg-white shadow-card px-4 py-2 rounded-full text-slate-600 hover:bg-slate-50"
                >
                  Cancel
                </button>
                <button
                  disabled={saving}
                  onClick={saveEdit}
                  className="text-sm font-medium bg-brand-600 hover:bg-brand-700 disabled:bg-slate-200 text-white px-5 py-2.5 rounded-full"
                >
                  {saving ? 'Saving…' : 'Save Changes'}
                </button>
              </>
            ) : (
              <button
                disabled={!content}
                onClick={() => {
                  if (!isInvoice) setDraft(content || '')
                  setEditing(true)
                }}
                className="text-sm font-medium bg-white shadow-card px-4 py-2 rounded-full text-slate-600 hover:bg-slate-50 disabled:opacity-50"
              >
                ✎ Edit
              </button>
            ))}
          <button
            disabled={!content}
            onClick={download}
            className="text-sm font-medium bg-white shadow-card px-4 py-2 rounded-full text-slate-600 hover:bg-slate-50 disabled:opacity-50"
          >
            ⬇ .md
          </button>
          {canEdit && (
            <button
              onClick={() => openDocumentPdf(params.baseName!, type).catch((e: any) => setError(e.message))}
              className="text-sm font-medium bg-brand-600 hover:bg-brand-700 text-white px-5 py-2.5 rounded-full"
            >
              ⬇ Download PDF
            </button>
          )}
        </div>
        <Card>
          {error && <div className="text-sm text-coral-600 bg-coral-50 rounded-2xl px-4 py-3 mb-4">{error}</div>}
          {!content && !error && <p className="text-sm text-slate-400">Loading document…</p>}
          {content && editing && isInvoice ? (
            <>
              <p className="text-sm text-brand-600 bg-brand-50 rounded-2xl px-4 py-3 mb-4">
                Click directly into the invoice below to edit it, then press Save Changes.
              </p>
              <HtmlFrame ref={frameRef} html={content} editable />
            </>
          ) : content && editing ? (
            <div className="prose-editor-container">
              <Editor
                ref={editorRef}
                initialValue={draft}
                initialEditType="wysiwyg"
                useCommandShortcut={true}
                hideModeSwitch={true}
                height="auto"
                minHeight="500px"
              />
            </div>
          ) : isInvoice ? (
            content && <HtmlFrame html={content} />
          ) : (
            content && (
              <article className="prose prose-slate prose-sm max-w-none prose-table:text-sm prose-headings:font-semibold">
                <ReactMarkdown
                  remarkPlugins={[remarkGfm]}
                  components={{
                    code(props) {
                      const { className, children, ...rest } = props as any
                      const match = /language-(\w+)/.exec(className || '')
                      if (match?.[1] === 'mermaid') {
                        return <Mermaid chart={String(children)} />
                      }
                      return (
                        <code className={className} {...rest}>
                          {children}
                        </code>
                      )
                    },
                    img(props) {
                      // The letterhead logo is embedded as a plain markdown
                      // image with no size hint, so it renders at whatever
                      // resolution the uploaded file happens to be — often
                      // far larger than the small header logo it's meant to
                      // be. Cap it the same way the PDF export already does
                      // (pdf_builder.py's _size_branding_images).
                      return <img {...props} className="max-h-16 w-auto inline-block" />
                    },
                  }}
                >
                  {content}
                </ReactMarkdown>
              </article>
            )
          )}
        </Card>
      </div>
    </div>
  )
}
