"""phase3_invoice_snapshots

Revision ID: 55e72f051073
Revises: b194a48eb47b
Create Date: 2026-08-17 16:03:09.522338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55e72f051073'
down_revision: Union[str, None] = 'b194a48eb47b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice_sequences',
    sa.Column('financial_year', sa.String(length=20), nullable=False),
    sa.Column('next_value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('financial_year')
    )
    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hsn_sac', sa.String(length=50), nullable=True))

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('client_address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('client_gstin', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('project_name', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_column('project_name')
        batch_op.drop_column('client_gstin')
        batch_op.drop_column('client_address')
        batch_op.drop_column('client_name')

    with op.batch_alter_table('invoice_items', schema=None) as batch_op:
        batch_op.drop_column('hsn_sac')

    op.drop_table('invoice_sequences')
    # ### end Alembic commands ###
